const ActionsType = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_CURRENT_LANG: "SET_CURRENT_LANG",
  SET_TABLE_DATA: "SET_TABLE_DATA",

  UPDATE_TICKET: "UPDATE_TICKET",
  API_ERROR: "API_ERROR",
  API_SUCCESS: "API_SUCCESS"
}

export default ActionsType
